BloggerBundle_homepage:
    path:     /
    defaults: { _controller: "BloggerBundle:Page:index" }
    requirements:
         methods:  GET

BloggerBundle_about:
    path:   /about
    defaults: { _controller: "BloggerBundle:Page:about" }
    requirements:
         methods:  GET

BloggerBundle_themes:
     path:   /themes
     defaults: { _controller: "BloggerBundle:Page:themes" }
     requirements:
        methods:  GET

BloggerBundle_blog_show:
    path:  /{id}
    defaults: { _controller: "BloggerBundle:Blog:show" }
    requirements:
        methods:  GET
        id: \d+